% Figure 7 in Heidemann et al. (2025)

% Stacked bar plots showing key predictors and explained variance for NW and NE Australian rainfall
% between October and April, as well as seasonal cycle of rainfall 

% 31/1/25 revision: display of seasonal cycle as box plots 


% input R2 values generated by examining output from
% stepwiselm_calculation_all_ts and manual_stepwiselm_func and taking
% process knowledge into account and correcting the order or predictors accordingly  


% set different colour for each key predictor 
not_r2_colour = [.92 .92 .92];
fill_color = [0 0 0];
CP_color = [0 .75 1]; % CP Index
EP_color = [0 .6 .8]; % EP Index
DMI_color = [.51 .44 1]; % DMI 
Coral_color = [0 .96 1]; % Coral Sea 
Timor_color =  [0 .53 .55];% Timor Sea 
Arafura_color = [0 .77 .8];  % Arafura and Gulf 
IOBW_color = [.54 .17 .89]; % IOBW .54 .17 .89
Nino34_color = [.09 .45 .8]; % Nino 3.4 lag-1
SM_color = [.56 .93 .56]; % soil moisture
ET_color = [.64 .8 .35]; % evapotranspiration
TPI_color = [0 0 .55]; % 13-year lowpass filtered TPI
NW_evap_color = [1 .93 .55]; % NW evap 
Ningaloo_color = [.55 .28 .54]; % Ningaloo Nino Index
TBO_color = [.69 .88 .9];% TBO
SAM_color = [1 .55 0]; % AM SAM 
MJO81_color = [.78 .08 .52];  % MJO phases 8,1
MJO456_color = [1 .2 .7];  % MJO phases 4,5,6
MJO_inactive_color = [.93 .51 .93];  % MJO inactive


%% 

% f = figure('pos',[10 10 1100 600])
% a = axes('Parent', f);

for i=1:2


    if i==1
        region='NW'
        % R2 values per predictor
        Sept_group = [0.35 0 0 0 0 0 0 0 0]; 
        Oct_group = [0.43 0.08 0 0 0 0 0 0 0]; 
        Nov_group = [0.2 0.08 0 0 0 0 0 0 0]; 
        Dec_group = [0.17 0.33 0 0 0 0 0 0 0]; 
        Jan_group = [0.28 0 0 0 0 0 0 0 0]; 
        Feb_group = [0.19 0.18 0.42 0 0 0 0 0 0]; 
        March_group = [0.31 0.4 0 0 0 0 0 0 0]; 
        April_group = [0.17 0.07 0 0 0 0 0 0 0]; 
        May_group = [0.18 0 0 0 0 0 0 0 0]; 
        
        
        C = [CP_color;Arafura_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            CP_color;Coral_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            MJO81_color;NW_evap_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            NW_evap_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            IOBW_color;MJO81_color;NW_evap_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            CP_color;NW_evap_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            MJO456_color;MJO81_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour]; 



    else
        i=2
        region='NE'
        
        Sept_group = [0.21 0.14 0 0 0 0 0 0]; 
        Oct_group = [0.3 0 0 0 0 0 0 0]; 
        Nov_group = [0.32 0.18 0 0 0 0 0 0];
        Dec_group = [0.24 0.22 0 0 0 0 0 0]; 
        Jan_group = [0.13 0.25 0 0 0 0 0 0]; 
        Feb_group = [0.13 0.19 0.15 0.15 0 0 0 0];
        March_group = [0.1 0.38 0 0 0 0 0 0]; 
        April_group = [0.15 0.11 0 0 0 0 0 0]; 
        May_group = [0.33 0 0 0 0 0 0 0]; 
        
        
        C = [Coral_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            CP_color;Coral_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            CP_color;NW_evap_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            SAM_color;NW_evap_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            IOBW_color;MJO81_color;SAM_color;NW_evap_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            CP_color;NW_evap_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour;...
            CP_color;MJO456_color;fill_color;fill_color;fill_color;fill_color;fill_color;fill_color;not_r2_colour]; 



    end 


n_months = 7;
n_bars = n_months; % number of months --> number of bars 
n_sections = length(Oct_group)+1; % number of individual sections (plus the colour for the 
% remaining explained variance to add up to 1


if i==1
    f1=figure
    
    b=bar([Oct_group 1-sum(Oct_group);Nov_group 1-sum(Nov_group);Dec_group 1-sum(Dec_group);...
        Jan_group 1-sum(Jan_group);Feb_group 1-sum(Feb_group);March_group 1-sum(March_group);April_group 1-sum(April_group)],'stacked');

    f = figure('pos',[10 10 1100 600])
    a = axes('Parent', f);

        for jj = 1:n_sections
        for ii=1:n_bars
            section=copyobj(b(jj), a);
            dummy=1:n_bars;
            dummy(dummy==ii)=[];
            section.YData(dummy) = 0;
   
            section.FaceColor = C(sub2ind([n_sections n_bars], jj, ii), :);
        end
        end
        ax1 = gca;
else
    i==2
    f1=figure
   
    b=bar([Oct_group 1-sum(Oct_group);Nov_group 1-sum(Nov_group);Dec_group 1-sum(Dec_group);...
        Jan_group 1-sum(Jan_group);Feb_group 1-sum(Feb_group);March_group 1-sum(March_group);April_group 1-sum(April_group)],'stacked');


    f = figure('pos',[10 10 1100 600])
    a = axes('Parent', f);
    for jj = 1:n_sections
        for ii=1:n_bars
            section=copyobj(b(jj), a);
            dummy=1:n_bars;
            dummy(dummy==ii)=[];
            section.YData(dummy) = 0;
  
            section.FaceColor = C(sub2ind([n_sections n_bars], jj, ii), :);
        end
    end
    ax2=gca;

end 


xticklabels({'Oct','Nov','Dec','Jan','Feb','Mar','Apr'})

if strcmp('NE',region)
    title('NE','FontSize',12)
else
    strcmp('NW',region)
    title('NW','FontSize',12)
    ylabel('R{^2}','FontSize',12,'FontWeight','bold')
end 

xlabel('Month','FontSize',12)

ylim([0 1])

close(f1)




    % % make new custom legend --> 
    hold on 
    h = zeros(3, 1);
    h(1) = plot(NaN,NaN,'or','Color',[CP_color]);
    set(h(1),'markerfacecolor',get(h(1),'color'));
    h(2) = plot(NaN,NaN,'or','Color',[Coral_color]);
    set(h(2),'markerfacecolor',get(h(2),'color'));
    h(3) = plot(NaN,NaN,'or','Color',[Arafura_color]);
    set(h(3),'markerfacecolor',get(h(3),'color'));
    h(4) = plot(NaN,NaN,'or','Color',[IOBW_color]);
    set(h(4),'markerfacecolor',get(h(4),'color'));
    h(5) = plot(NaN,NaN,'or','Color',[MJO456_color]);
    set(h(5),'markerfacecolor',get(h(5),'color'));
    h(6) = plot(NaN,NaN,'or','Color',[MJO81_color]);
    set(h(6),'markerfacecolor',get(h(6),'color'));
    h(7) = plot(NaN,NaN,'or','Color',[SAM_color]);
    set(h(7),'markerfacecolor',get(h(7),'color'));
    h(8) = plot(NaN,NaN,'or','Color',[NW_evap_color]);
    set(h(8),'markerfacecolor',get(h(8),'color'));
    h(9) = plot(NaN,NaN,'or','Color',[not_r2_colour]);
    set(h(9),'markerfacecolor',get(h(9),'color'));
    
  
    
%   legend
    lgd = legend(h,'CP Index','Coral Sea','Arafura Sea','IOBW',...
        'MJO phases 4,5,6','MJO phases 8,1','AM SAM','NW oceanic evaporation','Not explained','FontSize',9,'Location','northwest')


end 

%% now plot both in one figure as subplots

fnew = figure('pos',[10 10 1000 500])
ax1_copy = copyobj(ax1,fnew);
a_sub=subplot(1,2,1,ax1_copy)

copies = copyobj([ax2,lgd],fnew);
ax2_copy = copies(1);
b_sub=subplot(1,2,2,ax2_copy)

% title for the whole figure 
sgtitle('Stepwise linear regression, key predictors (1975-2023)','FontSize',15,'FontWeight','bold')

% set position and size of graphs 
set(a_sub,'Position',[0.1 0.1 0.42 0.69]);
set(b_sub,'Position',[0.56 0.1 0.42 0.69]);

% add a,b labels
annotation('textbox',[.09 .69 .1 .2],'String','(a)','FontSize',14,'FontWeight','bold','EdgeColor','none')
annotation('textbox',[.55 .69 .1 .2],'String','(b)','FontSize',14,'FontWeight','bold','EdgeColor','none')



%% next load data for display of seasonal cycle -  also for 1975 to 2023

% update during revisions: display the seasonal cycle as box plots. Hence
% need data vector for each month rather than means and standard
% deviations! 

time_period = '1975-2023'


load 'AWAP_rainfall_1900_2023.mat' 

input_rainfall_1 = precip(:,:,:,76:123);

length_years = size(input_rainfall_1,4);

[Lat,Lon] = meshgrid(lat,lon);

% mask out ocean grid points

[Lat,Lon] = meshgrid(lat,lon);
land = island(Lat, Lon);

rainfall_land = zeros(size(input_rainfall_1));

for i = 1 : 12 

input_rainfall = squeeze(input_rainfall_1(:,:,i,:));
land_3D= repmat(land,1,1,size(input_rainfall,3));
input_rainfall(land_3D==0) = NaN;

rainfall_land(:,:,i,:) = input_rainfall;

end 

Rainfall_climatology = squeeze(nanmean(rainfall_land,4));

idx_east = lon >= 135;
idx_east = find(idx_east ==1);

idx_west = lon < 135; 
idx_west = find(idx_west ==1);

idx = lat >= -20;
% find index for all latitude values bigger than or equal to -20 
lat_idx = find(idx==1);

clear precip
clear input_rainfall_1
clear input_rainfall

for i = 1:2 

    if i==1;
    region= 'Northeast';
    else
        i==2;
    region= 'Northwest';
    end 

% save NE and NW 
if strcmp('Northeast',region)
    lon_idx = idx_east;
    
    % area averaged rainfall 
    rainfall_NE = nanmean(rainfall_land(lon_idx,lat_idx,:,:),1);
    rainfall_NE=squeeze(nanmean(rainfall_NE,2));

    % only October to April 
    % recenter the data 

    rainfall_NE_1 = rainfall_NE(10:12,:);
    rainfall_NE_2 = rainfall_NE(1:4,:);
    rainfall_NE_Oct_Apr = [rainfall_NE_1;rainfall_NE_2];

else
    strcmp('Northwest',region)
    lon_idx = idx_west;
    

    % area averaged rainfall 
    rainfall_NW = nanmean(rainfall_land(lon_idx,lat_idx,:,:),1);
    rainfall_NW=squeeze(nanmean(rainfall_NW,2));

    % only October to April 
    % recenter the data 

    rainfall_NW_1 = rainfall_NW(10:12,:);
    rainfall_NW_2 = rainfall_NW(1:4,:);
    rainfall_NW_Oct_Apr = [rainfall_NW_1;rainfall_NW_2];
    

end



end 




%%
fnew = figure('pos',[10 10 1000 800])

a_sub=subplot(2,2,1)

ha = fill([2.5,2.5,6.5,6.5],[-50 550 550 -50],rgb('light blue')) % DJFM
ha.FaceAlpha =  0.4;
ha.EdgeColor = "none"

hold on 
bx=boxplot(rainfall_NW_Oct_Apr','Symbol',"o") % change outliner symbol and color
set(bx(6,:), 'LineWidth', 1.5); % each number corresponds to some part of the box plot
% 5 is the box outline, 6 is the median line, 7 is the marker for outliers 
set(bx(7,:), 'MarkerEdgeColor', [.8 .15 .15]); 

ylabel('mm month^{-1}')
title('NW annual cycle')

xticklabels({'Oct','Nov','Dec','Jan','Feb','Mar','Apr'})
% xlim([1 7])
ylim([-10 520])



b_sub=subplot(2,2,2)

ha = fill([2.5,2.5,6.5,6.5],[-50 550 550 -50],rgb('light blue')) % DJFM
ha.FaceAlpha =  0.4;
ha.EdgeColor = "none"

hold on 
bx2=boxplot(rainfall_NE_Oct_Apr','Symbol',"o")
set(bx2(6,:), 'LineWidth', 1.5);
set(bx2(7,:), 'MarkerEdgeColor', [.8 .15 .15]);

title('NE annual cycle')

xticklabels({'Oct','Nov','Dec','Jan','Feb','Mar','Apr'})
ylim([-10 520])

hold on 


legend('monsoon season','Location','northwest','FontSize',8)

ax1_copy = copyobj(ax1,fnew);
c_sub=subplot(2,2,3,ax1_copy)

copies = copyobj([ax2,lgd],fnew);
ax2_copy = copies(1);
d_sub=subplot(2,2,4,ax2_copy)

% title for the whole figure 
sgtitle('Stepwise linear regression, key predictors (1975-2023)','FontSize',15,'FontWeight','bold')

% set position and size of graphs 
set(a_sub,'Position',[0.14 0.59 0.34 0.27]);
set(b_sub,'Position',[0.6 0.59 0.34 0.27]);

set(c_sub,'Position',[0.1 0.1 0.42 0.40]);
set(d_sub,'Position',[0.56 0.1 0.42 0.40]);

% add a,b labels
annotation('textbox',[.09 .7 .1 .2],'String','(a)','FontSize',14,'FontWeight','bold','EdgeColor','none')
annotation('textbox',[.55 .7 .1 .2],'String','(b)','FontSize',14,'FontWeight','bold','EdgeColor','none')

annotation('textbox',[.09 .34 .1 .2],'String','(c)','FontSize',14,'FontWeight','bold','EdgeColor','none')
annotation('textbox',[.55 .34 .1 .2],'String','(d)','FontSize',14,'FontWeight','bold','EdgeColor','none')




%% save 

set(gcf,'InvertHardCopy','off');
set(gcf,'color','w');

fname_str = ['Figure_7_Stacked_bar_plots_revised']
print(fname_str,'-dtiff','-r300')


